export const SITE_CONFIG = {
  name: 'Hugo Gómez',
  fullName: 'Hugo Gómez',
  title: 'Ortodoncia',
  tagline: 'Especialista en Ortodoncia · Comunidad Valenciana',
  phone: '620 110 833',
  phoneHref: 'tel:+34620110833',
  email: 'hgomez@hgortodoncia.com',
  company: '',
  siteUrl: 'https://www.hugogomezortodoncia.es',
  locale: 'es_ES',
  lang: 'es',
  description:
    'Hugo Gómez, ortodoncista especialista en la Comunidad Valenciana. Ortodoncia con alineadores Invisalign®, brackets de autoligado y tecnología digital. Más de 10 años de experiencia.',
  keywords: [
    'ortodoncista Valencia',
    'ortodoncia Comunidad Valenciana',
    'Invisalign Valencia',
    'ortodoncista especialista Valencia',
    'ortodoncia digital Valencia',
    'brackets autoligado Valencia',
    'alineadores invisibles Valencia',
    'ortodoncia invisible Valencia',
    'ortodoncia adultos Valencia',
    'ortodoncia infantil Valencia',
    'aparatos dientes Valencia',
    'dientes apiñados ortodoncia',
    'Invisalign o brackets',
    'ortodoncista cerca de mí Valencia',
    'ortodoncista Moncada',
    'ortodoncista Museros',
    'ortodoncista Benetússer',
    'ortodoncista Albaida',
  ],
  experience: {
    years: 10,
    casesPerYear: 150,
    clinicsCount: 4,
  },
} as const;

export const CLINICS = [
  {
    name: 'Clínica Dental Font de la Rosa',
    city: 'Museros',
    province: 'Valencia',
    since: 2016,
    lat: 39.5373,
    lng: -0.3541,
  },
  {
    name: 'Clínica Dental Moncadent',
    city: 'Moncada',
    province: 'Valencia',
    since: 2018,
    lat: 39.5488,
    lng: -0.3952,
  },
  {
    name: 'Clínica Dental Benetússer',
    city: 'Benetússer',
    province: 'Valencia',
    since: 2020,
    lat: 39.4266,
    lng: -0.3979,
  },
  {
    name: 'Clínica Boronat',
    city: 'Albaida',
    province: 'Valencia',
    since: 2020,
    lat: 38.8432,
    lng: -0.5162,
  },
] as const;

export const NAV_ITEMS = [
  { label: 'Inicio', href: '/' },
  { label: 'Sobre mí', href: '/sobre-mi' },
  { label: 'Tratamientos y casos', href: '/tratamientos' },
  { label: 'Dónde encontrarme', href: '/donde-colaboro' },
  { label: 'Contacto', href: '/contacto' },
] as const;
